Complete mobile version by by creating Contact form and footer
tsigewossne/portfolio pull request #3
Opened 2023-06-06 12:00 UTC by tsigewossne

### In this point Have created
-contact form
-Required validations
-footer for the page

2023-06-06 19:05 UTC, Bantealem requested changes
# Status: Required Changes
Hi @tsigewossne 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [x] No Linters error
- [x] Correct Gihub flow
- [x]  Professional README.

## Required Changes ♻️
- [ ] Please make sure your project design is the same as the Figma design according to the project requirement.
![image](https://github.com/tsigewossne/portfolio/assets/101523582/5e90df05-7fa5-4471-9dd7-f7d6d7d1243f)
Your design
![Screenshot from 2023-06-06 21-46-39](https://github.com/tsigewossne/portfolio/assets/101523582/be0fcff5-eb81-4e21-a482-48489c77d902)
Figma design
![Screenshot from 2023-06-06 21-57-34](https://github.com/tsigewossne/portfolio/assets/101523582/abfb7ad8-99fb-4031-a512-1a8e6e4cbc22)

Kindly, implement all the colours, margins, texts, images etc.
Kindly, implement the button interaction based on the Figma design

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 19:05 UTC, Bantealem commented on index.html
> +              <input type="email" id="email" name="lastname" placeholder="Your last name.." required>
You have done a great job. Please make sure the `placeholder` is the same as the input. In this case, the `placeholder` for the email should be `email` since the input is asking to fill in the email. Kindly, fix it.

2023-06-06 19:05 UTC, Bantealem commented on index.html
> +              <input type="text" maxlength="30" id="fname" name="fullname" placeholder="Full name" required>
Please make sure you used the correct `formspree`  id. Currently, I can't send the message via your portfolio.  You can [create here](https://formspree.io/html)

2023-06-07 14:21 UTC, tsigewossne commented
## Thanks @Bantealem 
### changes I have made
-Fit Figma design by checking styles
-correct placeholder for form elements
-Add footer (horizontal line)

2023-06-07 14:32 UTC, LionRouge1 approved these changes
Hi @tsigewossne, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-06-07 14:43 UTC, merged